Name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        id: build_debug
        run: ./gradlew :app:assembleDebug --no-daemon
        continue-on-error: true

      - name: Build Release APK
        id: build_release
        run: ./gradlew :app:assembleRelease --no-daemon
        continue-on-error: true

      - name: Upload Debug APK
        if: steps:build_debug:outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: OpenStore-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Release APK
        if: steps:build_release:outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: OpenStore-release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Check Build Status
        if: steps:build_debug:outcome == 'failure' && steps:build_release:outcome == 'failure'
        run: exit 1
